language: cpp

env:
  global:
    - BIN=switch-lan-play

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode9.4

addons:
  homebrew:
    update: true
    packages:
      - libuv

before_script:
  - echo "Using tag $TRAVIS_TAG"
  - if [[ "$TRAVIS_TAG" == "" ]]; then export TAGNAME="nightly" && export NIGHTLY="-nightly" ; else export TAGNAME="$TRAVIS_TAG" && export NIGHTLY="" ; fi
  - echo "TAGNAME $TAGNAME NIGHTLY $NIGHTLY"
  - git submodule init ; git submodule update

script:
  - mkdir build
  - cd build
  - cmake .. && make -j4

# deploy:
#   skip_cleanup: true
#   provider: releases
#   draft: false
#   prerelease: true
#   api_key:
#     secure: 123
#   file:
#     - "${FILE_TO_UPLOAD}"
#   on:
#     all_branches: true
#     tags: true
